### ISSUE TITLE
JSONError for /get_data on staging - Individual Section

### ISSUE THREAD

**Issue by carlosmouracorreia** [FranMacedo/gestoremoto#18]
@FranMacedo I think this one is one you because of some non deployed (yet to restart Django) staging branch stuff? Might be on me because I've updated Nginx stuff/containers but all the static files look good.

Just for the record , as I can look into it tomorrow. (15-06)

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/6900758/84607832-637b0700-aea7-11ea-8202-6680f047f353.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/6900758/84607848-71c92300-aea7-11ea-9ac9-9a580668c9bb.png">

**Comment by FranMacedo** [comment]
There's no staging stuff left from my side, last week we merged everything that I had. That error does not happen on my machine!

**Comment by FranMacedo** [comment]
I think it's due to missing token:
![Capture](https://user-images.githubusercontent.com/54102462/84651311-9d78f700-af01-11ea-8304-d5f33603eeea.JPG)

**Comment by carlosmouracorreia** [comment]
Deactivate the module will most likely fix it ( I had activated it for the ticket #6) Thanks for the debugging!
